[package]
name = "database"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "1.3"
pest = "2.7"
pest_derive = "2.7"
lazy_static = "1.4"
